name: CI/CD Multizone

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build-master-zone:
    runs-on: ubuntu-latest
    environment: Production – master-zones
    defaults:
      run:
        working-directory: ./master-zone
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        env:
          NEXT_PUBLIC_HOME_URL: ${{ vars.NEXT_PUBLIC_HOME_URL }} # Dùng vars nếu lưu ở Variables
          NEXT_PUBLIC_BLOG_URL: ${{ vars.NEXT_PUBLIC_BLOG_URL }}
        run: bun run build

  build-blog-zone:
    runs-on: ubuntu-latest
    environment: Production – blogs-zones
    defaults:
      run:
        working-directory: ./blog-zone
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        env:
          NEXT_PUBLIC_HOME_URL: ${{ vars.NEXT_PUBLIC_HOME_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ vars.NEXT_PUBLIC_BLOG_URL }}

          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}

          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        run: bun run build
