name: CI/CD Multizone

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build-master-zone:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./master-zone
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create .env.production
        env:
          NEXT_PUBLIC_HOME_URL: ${{ secrets.NEXT_PUBLIC_HOME_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
        run: |
          echo "NEXT_PUBLIC_HOME_URL=${NEXT_PUBLIC_HOME_URL:-https://nextdi.io.vn}" >> .env.production
          echo "NEXT_PUBLIC_BLOG_URL=${NEXT_PUBLIC_BLOG_URL:-https://blog.nextdi.io.vn}" >> .env.production

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

  build-blog-zone:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blog-zone
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create .env.production
        env:
          NEXT_PUBLIC_HOME_URL: ${{ secrets.NEXT_PUBLIC_HOME_URL }}
          NEXT_PUBLIC_BLOG_URL: ${{ secrets.NEXT_PUBLIC_BLOG_URL }}
        run: |
          echo "NEXT_PUBLIC_HOME_URL=${NEXT_PUBLIC_HOME_URL:-https://nextdi.io.vn}" >> .env.production
          echo "NEXT_PUBLIC_BLOG_URL=${NEXT_PUBLIC_BLOG_URL:-https://blog.nextdi.io.vn}" >> .env.production

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
